Add php 7.3
indragunawan/docker-nginx-php pull request #3
Opened 2019-03-02 10:57 UTC by nipeharefa

2019-03-04 07:47 UTC, IndraGunawan requested changes

2019-03-04 07:47 UTC, IndraGunawan commented on ubuntu-php7.2/entrypoint.sh
> +        echo "Invalid type DOMAIN_$count = $DOMAIN_TYPE, available type (php|static|symfony|symfony4|rewrite_index)" >&2
di 7.2 udah bisa untuk sf4 juga?

2019-03-04 07:47 UTC, IndraGunawan commented on ubuntu-php7.3/Dockerfile
> +LABEL maintainer="Indra Gunawan <guind.online@gmail.com>"
ini `maintainer` nya buat nama mu aja @nipeharefa

2019-03-04 07:56 UTC, nipeharefa commented on ubuntu-php7.2/entrypoint.sh
> +        echo "Invalid type DOMAIN_$count = $DOMAIN_TYPE, available type (php|static|symfony|symfony4|rewrite_index)" >&2
Kantor sebelumnya pake php 7.2 sf4 :+1:

2019-03-04 07:56 UTC, nipeharefa commented on ubuntu-php7.3/Dockerfile
> +LABEL maintainer="Indra Gunawan <guind.online@gmail.com>"
Oke sip

2019-03-05 05:06 UTC, nipeharefa commented on ubuntu-php7.3/Dockerfile
> +LABEL maintainer="Indra Gunawan <guind.online@gmail.com>"
Cek lagi ya mas @IndraGunawan

2019-03-05 06:17 UTC, IndraGunawan approved these changes

2019-03-05 06:17 UTC, merged